### ISSUE TITLE
Don't install plugin on insomnia

### ISSUE THREAD

**Issue by cavoixanha** [StuartChartersE22/insomnia-plugin-testing#1]
Insomnia version: v6.5.4

```
Yarn error {"type":"warning","data":"package.json: No license field"}
```

**Comment by StuartChartersE22** [comment]
Thanks for raising this I will get the license field added

**Comment by StuartChartersE22** [comment]
I have looked into this issue. On the npm page for downloading the plugin, the license is clearly stated. This is populated from the license field in the package.json. Could you indicate where you are getting this error from?

**Comment by cavoixanha** [comment]
![image](https://user-images.githubusercontent.com/11247240/62339454-43985a00-b506-11e9-9a4b-da6ddd4d88a2.png)

**Comment by StuartChartersE22** [comment]
Thank you for the response. I removed my installation of the plugin from insomnia and re-installed it using insomnia-plugin-testing. No error came up. I am on Insomnia 6.5.4 on Ubuntu 18.04.2 LTS. What OS are you using? Have you been able to install other plugins since seeing this problem?

**Comment by cavoixanha** [comment]
I use Ubuntu 16.04.6 LTS and Insomnia 6.5.4
